text.quote.patterns <- list(
  list(s = "(?<=^|\\W)'", e = "(?<=\\w)'", min_words = 3L)
  , list(s = '"', e = '"', min_words = 3L)
  , list(s = "‘", e = "’(?=\\W|$)", min_words = 3L)
  , list(s = "“", e = "”", min_words = 3L)
  , list(s = "”", e = "“", min_words = 3L)
  , list(s = "’", e = "‘", min_words = 3L)
  , list(s = "‚", e = "‘", min_words = 3L)
  , list(s = "„", e = "“", min_words = 3L)
  , list(s = '«', e = '»', min_words = 3L)
  , list(s = '»', e = '«', min_words = 3L)
  , list(s = "″", e = "″", min_words = 3L)
)
usethis::use_data(text.quote.patterns, overwrite = TRUE)
